server:
  prot: 8081

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  tomcat:
    initSQL: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    # server alias
    instance-id: dept8001
    # show name is ip
    prefer-ip-address: true
info:
  app.name: thisName
  company.name: www.liangzisong.com
  build.artifactId: ${artifactId}
  build.version: ${version}